receptor = /Users/max/Desktop/HIV_Selectivity_Project/01_proteins/bace1.pdbqt
center_x = 10.086
center_y = -2.802
center_z = -0.337
size_x = 22.6
size_y = 33.4
size_z = 22.5
exhaustiveness = 8
num_modes = 9
