receptor = /Users/max/Desktop/HIV_Selectivity_Project/01_proteins/cathepsin_d.pdbqt
center_x = 20.298
center_y = 95.89
center_z = 9.058
size_x = 22.5
size_y = 27.8
size_z = 22.5
exhaustiveness = 8
num_modes = 9
