receptor = /Users/max/Desktop/HIV_Selectivity_Project/01_proteins/hiv_protease.pdbqt
center_x = 10.892
center_y = 23.057
center_z = 3.736
size_x = 25.1
size_y = 22.5
size_z = 22.5
exhaustiveness = 8
num_modes = 9
